export * from "@/admin/admin/home";
 export * from "@/admin/admin/tables";
export * from "@/admin/admin/notifications";
export * from "@/admin/admin/works";
export * from "@/admin/admin/tools";
export * from "@/admin/admin/tabs";
export * from "@/admin/admin/addLocation";
export * from "@/admin/admin/hisobot";
export * from "@/admin/admin/observes";
