export * from "@/admin/admin/home";
export * from "@/admin/admin/profile";
export * from "@/admin/admin/tables";
export * from "@/admin/admin/notifications";
export * from "@/admin/admin/works";
export * from "@/admin/admin/tools";
export * from "@/admin/admin/hiddenKD";
export * from "@/admin/admin/tabs";
export * from "@/admin/admin/addLocation";
